[user]
	name = Hayden Perry
	email = haydencwperry@gmail.com
[core]
	editor = nvim
	sshCommand = ssh -i ~/.ssh/id_rsa -F /dev/null
[pull]
	rebase = true
[push]
	recurseSubmodules = on-demand
[commit]
	# gpgsign = true
[gpg]
	program = gpg2
[credential]
	helper = cache
