[theme]
name = "gruvbox-dark"

[icons]
name = "none"

[theme.overrides]
separator_fg = "#FFFFFF"
separator = " | "

[[block]]
block = "bluetooth"
mac = "DC:2C:26:B6:B0:6B"

[[block]]
block = "disk_space"
path = "/"
alias = "ROOT"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
